# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'XHKitUIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "XiangHongKit"
  # Pods for XHKitUIDemo

  target 'XHKitUIDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XHKitUIDemoUITests' do
    # Pods for testing
  end

end
